module.exports = [
  "Canaima",
  "La Floresta de La Sabana",
  "Torca",
  "Altos de Serrezuela",
  "Balcones de Vista Hermosa",
  "Balmoral Norte",
  "Buenavista",
  "Chaparral",
  "El Codito",
  "El Refugio de San Antonio",
  "El Verbenal",
  "Horizontes",
  "La Estrellita",
  "La Frontera",
  "La Llanurita",
  "Los Consuelos",
  "Maranta",
  "Maturin",
  "Medellin",
  "Mirador del Norte",
  "Nuevo Horizonte",
  "San Antonio Norte",
  "Santandersito",
  "Tibabita",
  "Vina del Mar",
  "Bosque de San Antonio",
  "Conjunto Camino del Palmar",
  "El Pite",
  "El Redil",
  "La Cita",
  "La Granja Norte",
  "La Uribe",
  "Los Naranjos",
  "San Juan Bosco",
  "Urbanizacion Los Laureles",
  "Ainsuca",
  "Altablanca",
  "Barrancas",
  "California",
  "Cerro Norte",
  "Danubio",
  "Don Bosco",
  "La Perla Oriental",
  "Las Areneras",
  "Milan",
  "Pradera Norte",
  "San Cristobal Norte",
  "Santa Teresa",
  "Soratama",
  "Torcoroma",
  "Villa Nydia",
  "Villa Oliva",
  "El Toberin",
  "Babilonia",
  "Darandelos",
  "Estrella del Norte",
  "Guanoa",
  "Jardin Norte",
  "La Liberia",
  "La Pradera Norte",
  "Las Orquideas",
  "Pantanito",
  "Santa Monica",
  "Villa Magdala",
  "Villas de Aranjuez",
  "Villas del Mediterraneo",
  "Zaragoza",
  "Acacias",
  "Antigua",
  "Belmira",
  "Bosque de Pinos",
  "Caobos Salazar",
  "Capri",
  "Cedritos",
  "Cedro Bolivar",
  "Cedro Golf",
  "Cedro Madeira",
  "Cedro Narvaez",
  "Cedro Salazar",
  "El Contador",
  "El Rincon de Las Margaritas",
  "La Sonora",
  "Las Margaritas",
  "Lisboa",
  "Los Cedros",
  "Los Cedros Oriental",
  "Montearroyo",
  "Nueva Autopista",
  "Nuevo Country",
  "Sierras del Moral",
  "Bella Suiza",
  "Bellavista",
  "Bosque Medina",
  "El Panuelito",
  "El Pedregal",
  "Escuela de Caballeria I",
  "Escuela de Infanteria",
  "Francisco Miranda",
  "Ginebra",
  "La Esperanza",
  "La Glorieta",
  "Las Delicias del Carmen",
  "Sagrado Corazon",
  "San Gabriel",
  "Santa Ana",
  "Santa Ana Occidental",
  "Santa Barbara",
  "Santa Barbara Alta",
  "Santa Barbara Oriental",
  "Unicerros",
  "Usaquen",
  "Country Club",
  "La Calleja",
  "La Carolina",
  "La Cristalina",
  "Prados del Country",
  "Recodo del Country",
  "Santa Coloma",
  "Soatama",
  "Toledo",
  "Torres del Country",
  "Vergel del Country",
  "Santa Barbara Occidental",
  "Campo Alegre",
  "Molinos del Norte",
  "Multicentro",
  "Navarra",
  "Rincon del Chico",
  "San Patricio",
  "Santa Barbara Central",
  "Santa Bibiana",
  "Santa Paula",
  "Chico Reservado",
  "Chico Alto",
  "El Nogal",
  "El Refugio",
  "La Cabrera",
  "Los Rosales",
  "Seminario",
  "Toscana",
  "La Esperanza Nororiental",
  "La Surena",
  "San Isidro",
  "San Luis Altos del Cabo",
  "Bosque Calderon",
  "Bosque Calderon Tejada",
  "Chapinero Alto",
  "El Castillo",
  "El Paraiso",
  "Emaus",
  "Granada",
  "Ingemar",
  "Juan XXIII",
  "La Salle",
  "Las Acacias",
  "Los Olivos",
  "Maria Cristina",
  "Mariscal Sucre",
  "Nueva Granada",
  "Palomar",
  "Pardo Rubio",
  "San Martin de Porres",
  "Villa Anita",
  "Villa del Cerro",
  "Antiguo Country",
  "Chico Norte",
  "Chico Norte II",
  "Chico Norte III",
  "Chico Occidental",
  "El Chico",
  "El Retiro",
  "Espartillal",
  "Lago Gaitan",
  "Porciuncula",
  "Quinta Camacho",
  "Cataluna",
  "Chapinero Central",
  "Chapinero Norte",
  "Marly",
  "Sucre",
  "La Merced",
  "Parque Central Bavaria",
  "San Diego",
  "Samper",
  "San Martin",
  "Bosque Izquierdo",
  "Germania",
  "La Macarena",
  "La Paz Centro",
  "La Perseverancia",
  "La Alameda",
  "La Capuchina",
  "Veracruz",
  "Las Nieves",
  "San Victorino",
  "Santa Ines",
  "Las Cruces",
  "San Bernardo",
  "Atanasio Girardot",
  "Cartagena",
  "El Balcon",
  "El Consuelo",
  "El Dorado",
  "El Guavio",
  "El Mirador",
  "El Rocio",
  "El Triunfo",
  "Fabrica de Loza",
  "Gran Colombia",
  "La Pena",
  "Los Laches",
  "Lourdes",
  "Ramirez",
  "San Dionisio",
  "Santa Rosa de Lima",
  "Vitelma",
  "Aguas Claras",
  "Altos del Zipa",
  "Amapolas",
  "Amapolas II",
  "Balcon de La Castana",
  "Bella Vista Sector Lucero",
  "Bellavista Parte Baja",
  "Bellavista Sur",
  "Bosque de Los Alpes",
  "Buenavista Suroriental",
  "Camino Viejo San Cristobal",
  "Cerros de San Vicente",
  "Ciudad de Londres",
  "Corinto",
  "El Balcon de La Castana",
  "El Futuro",
  "El Ramajal",
  "Gran Colombia",
  "Horacio Orjuela",
  "La Castana",
  "La Cecilia",
  "La Gran Colombia",
  "La Herradura",
  "La Joyita Centro",
  "La Playa",
  "La Roca",
  "La Sagrada Familia",
  "Las Acacias",
  "Las Columnas",
  "Las Mercedes",
  "Laureles Sur Oriental II",
  "Los Alpes",
  "Los Alpes Futuro",
  "Los Arrayanes Sector Santa Ines",
  "La Roca",
  "Los Laureles Sur Oriental I",
  "Macarena Los Alpes",
  "Manantial",
  "Manila",
  "Miraflores",
  "Molinos de Oriente",
  "Montecarlo",
  "Nueva Espana",
  "Nueva Espana Parte Alta",
  "Ramajal",
  "Rincon de La Victoria",
  "Sagrada Familia",
  "San Blas",
  "San Blas II",
  "San Cristobal Alto",
  "San Cristobal Viejo",
  "San Pedro Sur Oriental",
  "San Vicente",
  "San Vicente Alto",
  "San Vicente Bajo",
  "San Vicente Sur Oriental",
  "Santa Ines",
  "Santa Ines Sur",
  "Terrazas de Oriente",
  "Triangulo",
  "Triangulo Alto",
  "Triangulo Bajo",
  "Vereda Altos de San Blas",
  "Vitelma",
  "Golconda",
  "Primero de Mayo",
  "Buenos Aires",
  "Calvo Sur",
  "La Maria",
  "Las Brisas",
  "Los Dos Leones",
  "Modelo Sur",
  "Narino Sur",
  "Quinta Ramos",
  "Republica de Venezuela",
  "San Cristobal Sur",
  "San Javier",
  "Santa Ana",
  "Santa Ana Sur",
  "Sosiego",
  "Velodromo",
  "Villa Albania",
  "Villa Javier",
  "Atenas",
  "20 de Julio",
  "Atenas I",
  "Ayacucho",
  "Barcelona",
  "Barcelona Sur",
  "Barcelona Sur Oriental",
  "Bello Horizonte",
  "Bello Horizonte III",
  "Cordoba",
  "El Angulo",
  "El Encanto",
  "Granada Sur",
  "Granada Sur III",
  "La Joyita",
  "La Serafina",
  "Managua",
  "Montebello",
  "San Isidro",
  "San Isidro I",
  "San Isidro II",
  "San Isidro Sur",
  "San Luis",
  "Sur America",
  "Villa de Los Alpes",
  "Villa de Los Alpes I",
  "Villa Nataly",
  "20 de Julio",
  "Altamira",
  "Altamira Chiquita",
  "Altos del Poblado",
  "Altos del Virrey",
  "Altos del Zuque",
  "Bellavista Parte Alta",
  "El Pilar",
  "Bellavista Sur Oriental",
  "Ciudadela Santa Rosa",
  "El Quindio",
  "El Recodo-Republica de Canada",
  "El Rodeo",
  "La Colmena",
  "La Gloria",
  "La Gloria Baja",
  "La Gloria MZ 11",
  "La Gloria Occidental",
  "La Gloria Oriental",
  "La Gloria San Miguel",
  "La Grovana",
  "La Victoria",
  "La Victoria II",
  "La Victoria III",
  "La Ye",
  "Las Gaviotas",
  "Las Guacamayas",
  "Las Guacamayas I",
  "Las Guacamayas II",
  "Las Guacamayas III",
  "Malvinas",
  "Miraflores",
  "Moralba",
  "Panorama",
  "Paseito III",
  "Puente Colorado",
  "Quindio",
  "Quindio I",
  "Quindio II",
  "San Jose",
  "San Jose Oriental",
  "San Jose Sur Oriental",
  "San Martin de Loba I",
  "San Martin de Loba II",
  "San Martin Sur",
  "San Miguel",
  "Antioquia",
  "Canada La Guira",
  "Canada La Guira II",
  "Canada-San Luis",
  "Chiguaza",
  "Ciudad de Londres",
  "El Paraiso",
  "El Pinar",
  "El Triunfo,Juan Rey",
  "La Belleza",
  "La Nueva Gloria",
  "La Nueva Gloria II",
  "La Peninsula",
  "La Sierra",
  "Los Libertadores",
  "Los Libertadores Sector El Tesoro",
  "Los Libertadores Sector La Colina",
  "Los Libertadores Sector San Ignacio",
  "Los Libertadores Sector San Isidro",
  "Los Libertadores Sector San Jose",
  "Los Libertadores Sector San Luis",
  "Los Libertadores Sector San Miguel",
  "Los Libertadores Bosque Diamante Triangulo",
  "Los Pinares",
  "Los Pinos",
  "Los Puentes",
  "Nueva Delhi",
  "Nueva Gloria",
  "Nueva Roma",
  "Nuevas Malvinas",
  "Republica del Canada",
  "Republica del Canada-El Pinar",
  "San Jacinto",
  "San Manuel",
  "San Rafael Sur Oriental",
  "San Rafael Usme",
  "Santa Rita I",
  "Santa Rita II",
  "Santa Rita III",
  "Santa Rita Sur Oriental",
  "Valparaiso",
  "Villa Angelica-Canada-La Guira",
  "Villa Aurora",
  "Villa del Cerro",
  "Villabell",
  "Yomasa",
  "Villa Angelica",
  "El Paraiso Sur Oriental I",
  "Juan Rey I",
  "Juan Rey II",
  "Villa Begonia",
  "Buenos Aires",
  "Costa Rica",
  "Dona Liliana",
  "El Bosque km 11",
  "Juan Jose Rondon",
  "Juan Jose Rondon II",
  "La Cabana",
  "La Esperanza",
  "La Flora-Parcelacion San Pedro",
  "Las Violetas",
  "Los Arrayanes",
  "Los Soches",
  "Tihuaque",
  "Union",
  "Villa Diana",
  "Villa Rosita",
  "Alaska",
  "Arrayanes",
  "Danubio Azul",
  "Daza Sector II",
  "Duitama",
  "El Porvenir",
  "El Porvenir II",
  "Fiscala II La Fortuna",
  "Fiscala Sector Centro",
  "La Fiscala-Los Tres Laureles",
  "La Fiscala-Lote 16",
  "La Fiscala-Lote 16A",
  "La Fiscala Sector Daza",
  "La Fiscala Sector Norte",
  "La Fiscala Sector Rodriguez",
  "La Morena I",
  "La Morena II",
  "La Morena II",
  "Nueva Esperanza",
  "San Martin",
  "Villa Neiza",
  "Picota Sur",
  "Porvenir",
  "Almirante Padilla",
  "Altos del Pino",
  "Arizona",
  "Barranquillita",
  "Benjamin Uribe",
  "Betania",
  "Betania II",
  "Bolonia",
  "Bulevar del Sur",
  "Casa Loma II",
  "Casa Rey",
  "Casaloma",
  "Compostela I",
  "Compostela II",
  "Compostela III",
  "El Bosque",
  "El Cortijo",
  "El Curubo",
  "El Jordan",
  "El Nevado",
  "El Pedregal",
  "El Recuerdo Sur",
  "El Refugio",
  "El Refugio Sector Santa Librada",
  "El Rosal-Mirador",
  "El Rubi II Sector",
  "Gran Yomasa I",
  "Gran Yomasa II",
  "La Andrea",
  "La Aurora",
  "La Cabana",
  "La Esperanza",
  "La Fortaleza",
  "La Regadera km 11",
  "La Regadera Sur",
  "Las Granjas de San Pedro",
  "Las Viviendas",
  "Los Tejares Sur II Sector",
  "Nuevo San Andres de Los Altos",
  "Olivares",
  "Salazar Salazar",
  "San Andres Alto",
  "San Felipe",
  "San Isidro Sur",
  "San Juan Bautista",
  "San Juan I",
  "San Juan II",
  "San Juan II",
  "San Juan III",
  "San Luis",
  "San Pablo",
  "Santa Librada",
  "Santa Librada-La Esperanza",
  "Santa Librada-La Surena",
  "Santa Librada-Los Tejares",
  "Santa Librada Norte",
  "Santa Librada-San Bernardino",
  "Santa Librada-San Francisco",
  "Santa Librada-Salazar Salazar",
  "Santa Librada Sector La Pena",
  "Santa Marta II",
  "Santa Martha",
  "Sierra Morena",
  "Tenerife II",
  "Urbanizacion Costa Rica-San Andres de los Altos",
  "Urbanizacion Brasilia II",
  "Urbanizacion Brasilia Sur",
  "Urbanizacion Cartagena",
  "Urbanizacion La Andrea",
  "Urbanizacion La Aurora II",
  "Urbanizacion Miravalle",
  "Urbanizacion Tequendama",
  "Valles de Cafam",
  "Vianey",
  "Villa Alejandria",
  "Villa Nelly",
  "Villas de Santa Isabel",
  "Villas del Eden",
  "Yomasita",
  "Alfonso Lopez Sector Charala",
  "Antonio Jose de Sucre I",
  "Antonio Jose de Sucre II",
  "Antonio Jose de Sucre III",
  "Bellavista Alta",
  "Bellavista II",
  "Bosque El Limonar",
  "Bosque El Limonar II",
  "Brazuelos",
  "Brazuelos Occidental",
  "Brazuelos-El Paraiso",
  "Brazuelos-La Esmeralda",
  "Centro Educativo San Jose",
  "Chapinerito",
  "Chico Sur",
  "Chico Sur II",
  "Ciudadela Cantarrana I",
  "Ciudadela Cantarrana II",
  "Ciudadela Cantarrana III",
  "Comuneros",
  "El Brillante",
  "El Espino",
  "El Mortino",
  "El Rubi",
  "El Tuno",
  "El Uval",
  "El Virrey Ultima Etapa",
  "Finca La Esperanza",
  "La Esmeralda-El Recuerdo",
  "La Esperanza km 10",
  "Las Brisas",
  "Las Flores",
  "Las Mercedes",
  "Lorenzo Alcantuz I",
  "Lorenzo Alcantuz II",
  "Los Altos del Brazuelo",
  "Marichuela III",
  "Monteblanco",
  "Montevideo",
  "Nuevo San Luis",
  "San Joaquin-El Uval",
  "Sector Granjas de San Pedro",
  "Tenerife",
  "Urbanizacion Chuniza I",
  "Urbanizacion Jaron Monte Rubio",
  "Urbanizacion Libano",
  "Urbanizacion Marichuela",
  "Usminia",
  "Villa Alemania",
  "Villa Alemania II",
  "Villa Anita Sur",
  "Villa Israel",
  "Villa Israel II",
  "Alfonso Lopez Sector Buenos Aires",
  "Alfonso Lopez Sector El Progreso",
  "Brisas del Llano",
  "El Nuevo Portal",
  "El Paraiso",
  "El Portal II Etapa",
  "El Progreso Usme",
  "El Refugio I",
  "El Refugio II",
  "El Triangulo",
  "El Uval II",
  "La Huerta",
  "La Orquidea Usme",
  "La Reforma",
  "Nuevo Porvenir",
  "Nuevo Progreso-El Progreso II",
  "Portal de La Vega",
  "Portal de Oriente",
  "Portal del Divino",
  "Puerta al Llano",
  "Puerta al Llano II",
  "Refugio I",
  "Villa Hermosa",
  "Arrayanes",
  "Bolonia",
  "El Bosque Central",
  "El Nuevo Portal II",
  "El Refugio I",
  "La Esperanza Sur",
  "Los Olivares",
  "Pepinitos",
  "Tocaimita Oriental",
  "Tocaimita Sur",
  "Ciudadela El Oasis",
  "Brisas del Llano",
  "Usme-Centro",
  "El Bosque km 11",
  "El Pedregal-La Lira",
  "El Salteador",
  "La Maria",
  "Fatima",
  "Isla del Sol",
  "Laguneta",
  "Nuevo Muzu",
  "Rincon de Muzu",
  "Rincon de Venecia",
  "Samore",
  "San Vicente Ferrer",
  "Tejar de Ontario",
  "Venecia",
  "Ciudad Tunal",
  "Abraham Lincoln",
  "San Benito",
  "San Carlos",
  "Tunjuelito",
  "Jardines del Apogeo",
  "El Motorista",
  "Industrial",
  "La Ilusion",
  "Nuevo Chile",
  "Olarte",
  "Villa del Rio",
  "Amaru",
  "Berlin",
  "Berlin de Bosa La Libertad III",
  "Betania",
  "Bosa Nova",
  "Bosa Nova II Sector",
  "Bosalinda (Holdebrando Olarte)",
  "Brasil",
  "Brasilia",
  "Campo Hermoso",
  "Casa Nueva",
  "Chicala",
  "Ciudadela La Libertad",
  "El Bosque de Bosa",
  "El Cauce",
  "El Diamante",
  "El Libertador",
  "El Paradero",
  "El Portal de La Libertad",
  "El Porvenir",
  "El Progreso",
  "El Recuerdo",
  "El Rincon de Bosa",
  "El Rodeo",
  "El Sauce",
  "Escocia",
  "Finca La Esperanza",
  "Holanda",
  "Hortelanos de Escocia",
  "Jorge Uribe Botero",
  "La Concepcion",
  "La Dulcinea",
  "La Esmeralda",
  "La Estanzuela I",
  "La Estanzuela II",
  "La Florida",
  "La Fontana de Bosa-La Libertad",
  "La Independencia",
  "La Libertad I",
  "La Libertad II",
  "La Libertad III",
  "La Libertad IV",
  "La Magnolia",
  "La Maria",
  "La Palma",
  "La Paz",
  "La Portada",
  "La Portadita",
  "La Veguita",
  "Las Margaritas",
  "Las Vegas",
  "Los Ocales",
  "Los Sauces",
  "Miami",
  "New Jersey",
  "Nuestra Senora de La Paz",
  "Nueva Escocia",
  "Nueva Esperanza",
  "Porvenir",
  "Potreritos",
  "San Antonio",
  "San Antonio de Bosa",
  "San Antonio de Escocia",
  "San Bernardino",
  "San Javier",
  "San Jorge",
  "San Juanito",
  "San Martin",
  "San Pedro",
  "Santa Ines",
  "Sauces",
  "Siracuza",
  "Tokio",
  "Vegas de Santana",
  "Villa Carolina",
  "Villa Clemencia",
  "Villa Colombia",
  "Villa de Los Comuneros",
  "Villa de Suaita",
  "Villa Magnolia",
  "Villa Natalia",
  "Villa Nohora",
  "Villa Sonia I",
  "Villa Sonia II",
  "Villas del Progreso",
  "Villas del Velero",
  "Campo Verde",
  "Andalucia I",
  "Andalucia II",
  "Antonia Santos",
  "Argelia",
  "Bosa",
  "Bosques de Meryland",
  "Brasilia-La Estacion",
  "Carlos Alban",
  "Charles de Gaulle",
  "Claretiano",
  "El Jardin",
  "El Llano",
  "El Palmar",
  "El Portal de Bosa",
  "El Povenir",
  "El Progreso",
  "El Retazo",
  "El Toche",
  "Getsemani",
  "Grancolombiano I",
  "Grancolombiano II",
  "Gualoche",
  "Hermanos Barragan",
  "Humberto Valencia",
  "Islandia",
  "Israelita",
  "Jimenez de Quesada",
  "Jose Antonio Galan",
  "Jose Maria Carbonel",
  "La Amistad",
  "La Azucena",
  "La Estacion",
  "La Riviera",
  "Laureles",
  "Llano Oriental",
  "Llanos de Bosa",
  "Manzanares",
  "Mitrani",
  "Naranjos",
  "Nueva Granada",
  "Bosa Palestina",
  "Paso Ancho",
  "Piamonte",
  "Primavera Sur",
  "San Eugenio",
  "San Pablo I",
  "San Pablo II",
  "San Pedro",
  "Santa Lucia",
  "Urbanizacion Acuarela",
  "Betania",
  "Vereda San Jose",
  "La Esperanza",
  "Villa Anny",
  "Villa Bosa",
  "Villa Nohora",
  "Xochimilco",
  "Caldas",
  "Antonio Narino",
  "Campo Hermoso",
  "Canaveralejo",
  "El Anhelo",
  "El Corzo",
  "El Porvenir",
  "El Recuerdo",
  "El Recuerdo de Santa Fe",
  "El Regalo",
  "La Arboleda",
  "La Cabana",
  "La Granjita",
  "La Suerte",
  "La Union",
  "Los Centauros",
  "Osorio X",
  "Osorio XIII",
  "Parcela El Porvenir",
  "San Bernardino II",
  "San Miguel",
  "Santa Fe I",
  "Santa Fe II",
  "Santa Fe III",
  "Santa Fe de Bosa",
  "Villa Alegre",
  "Villa Alegria",
  "Villa Esmeralda",
  "Villa Karen",
  "\tEl Matorral",
  "El Matorral de San Bernardino",
  "El Triunfo",
  "El Triunfo de San Bernardino",
  "La Vega de San Bernardino Bajo",
  "Potreritos",
  "San Bernardino Sector Potrerito",
  "San Bernardino XIX",
  "San Bernardino XVI",
  "San Bernardino XVII",
  "San Bernardino XVIII",
  "San Bernardino XXII",
  "San Bernardino XXV",
  "Ciudadela el Recreo",
  "Aloha Norte",
  "Agrupacion de Vivienda Pio XII",
  "Andalucia I",
  "Andalucia II",
  "Bavaria Techo II",
  "Bosques de Castilla",
  "Castilla La Nueva",
  "Castilla Los Mandriles",
  "Castilla Real",
  "Castilla Reservado",
  "Catania",
  "Catania-Castilla",
  "Ciudad Don Bosco",
  "Ciudad Favidi",
  "Ciudad Techo",
  "El Castillo",
  "El Condado",
  "El Portal de las Americas",
  "El Rincon de Castilla",
  "El Rincon de Los Angeles",
  "El Tintal",
  "El Vergel",
  "Lagos de Castilla",
  "Las Dos Avenidas I",
  "Las Dos Avenidas II Etapa",
  "Monterrey",
  "Multifamiliares El Ferrol",
  "Osorio",
  "Oviedo",
  "Pio XII",
  "San Jose Occidental",
  "Santa Catalina I",
  "Santa Catalina II",
  "Valladolid",
  "Villa Alsacia",
  "Villa Castilla",
  "Villa Galante",
  "Villa Liliana",
  "Villa Mariana",
  "Vision de Colombia",
  "Agrupacion Pio X",
  "Agrupacion Multifamiliar Villa Emilia",
  "Alferez Real",
  "Americas Central",
  "Americas Occidental I",
  "Americas Occidental II",
  "Americas Occidental III Etapa",
  "Antiguo Hipodromo de Techo II Etapa",
  "Banderas",
  "Carvajal II Sector",
  "Centroamericas",
  "Ciudad Kennedy",
  "El Rincon de Mandalay",
  "Floresta Sur",
  "Fundadores",
  "Glorieta de las Americas",
  "Hipotecho",
  "Igualdad I",
  "Igualdad II",
  "La Llanura",
  "Las Americas",
  "Los Sauces",
  "Mandalay",
  "Marsella III",
  "Nueva Marsella I",
  "Nueva Marsella II",
  "Nueva Marsella III",
  "Provivienda Oriental",
  "Santa Rosa de Carvajal",
  "Villa Adriana",
  "Villa Claudia",
  "Alqueria de la Fragua",
  "Bombay",
  "Carimagua I",
  "Carvajal",
  "Carvajal Osorio",
  "Carvajal Techo",
  "Condado El Rey",
  "Delicias",
  "Desarrollo Nueva York",
  "El Pencil",
  "El Progreso I",
  "El Progreso II",
  "El Triangulo",
  "Floralia I",
  "Floralia II",
  "Gerona",
  "Guadalupe",
  "La Chucua",
  "Las Torres",
  "Los Cristales",
  "Lucerna",
  "Milenta",
  "Nueva York",
  "Provivienda",
  "Provivienda Occidental",
  "Salvador Allende",
  "San Andres I",
  "San Andres II",
  "Talavera de la Reina",
  "Tayrona Comercial",
  "Valencia-La Chucua",
  "Villa Nueva",
  "Abraham Lincoln",
  "Casablanca I",
  "Casablanca II",
  "Casablanca III",
  "Casablanca IV",
  "Casablanca 32",
  "Casablanca 33",
  "Ciudad Kennedy Central",
  "Ciudad Kennedy Norte",
  "Ciudad Kennedy Occidental",
  "Ciudad Kennedy Oriental",
  "Ciudad Kennedy Sur",
  "El Descanso",
  "La Giraldilla",
  "Miraflores Kennedy",
  "Multifamiliar Techo",
  "Nuevo Kennedy",
  "Pastrana",
  "Techo",
  "Puerto Jose de Caldas",
  "Alameda de Timiza",
  "Alfonso Montana",
  "Berlin",
  "Boita I",
  "Boita II",
  "Casa Loma",
  "Catalina",
  "Catalina II",
  "El Comite",
  "El Jordan",
  "El Palenque",
  "El Porvenir",
  "El Rubi",
  "Jacqueline",
  "Juan Pablo I",
  "La Cecilia",
  "La Unidad",
  "Lago Timiza I",
  "Lago Timiza II",
  "Las Luces",
  "Moravia II",
  "Nuevo Timiza",
  "Onasis",
  "Pastrana",
  "Pastranita II",
  "Perpetuo Socorro",
  "Prados de Kennedy",
  "Roma",
  "Roma II",
  "Sagrado Corazon",
  "San Martin de Porres",
  "Santa Catalina",
  "Timiza",
  "Tonoli",
  "Tocarema",
  "Tundama",
  "Vasconia II",
  "Villa de los Sauces",
  "Villa Rica",
  "Santa Paz-Santa Elvira",
  "Vereda El Tintal",
  "Urbanizacion Unir Uno",
  "Calandaima",
  "Conjunto Residencial Prados de castilla I",
  "Conjunto Residencial Prados de castilla II",
  "Conjunto Residencial Prados de castilla III",
  "Conjunto Residencial Gerona del Tintal",
  "Galan",
  "Osorio",
  "Santa Fe del Tintal",
  "Tintala",
  "Ciudadela Tierra Buena",
  "Ciudadela Primavera",
  "Cayetano Canizares",
  "Chucua de la Vaca",
  "El Amparo",
  "El Llantito",
  "El Olivo",
  "El Saucedal",
  "La Concordia",
  "La Esperanza",
  "La Maria",
  "Llano Grande",
  "Maria Paz",
  "Pinar del Rio",
  "San Carlos",
  "Villa de la Loma",
  "Villa de la Torre",
  "Villa Emilia",
  "Vista Hermosa",
  "Alfonso Lopez Michelsen",
  "Britalita",
  "Calarca I",
  "Calarca II",
  "Casablanca Sur",
  "Class",
  "El Almenar",
  "El Carmelo",
  "Gran Britalia",
  "La Esperanza",
  "La Maria",
  "Pastranita",
  "Santa Maria de Kennedy",
  "Vegas de Santa Ana",
  "Villa Andrea",
  "Villa Anita",
  "Villa Nelly",
  "Villa Zarzamora",
  "Villas de Kennedy",
  "Altamar",
  "Avenida Cundinamarca",
  "Barranquillita",
  "Bellavista",
  "Campo Hermoso",
  "Ciudad de Cali",
  "Ciudad Galan",
  "Ciudad Granada",
  "Dindalito",
  "El Paraiso",
  "El Patio",
  "El Rosario",
  "El Saucedal",
  "El Triunfo",
  "Horizonte Occidente",
  "Jazmin Occidental",
  "La Rivera",
  "Las Acacias",
  "Las Brisas",
  "Las Palmeras",
  "Los Almendros",
  "Palmitas",
  "Patio Bonito I",
  "Patio Bonito II",
  "Patio Bonito III",
  "Puente La Vega",
  "San Dionisio",
  "San Marino",
  "Santa Monica",
  "Sumapaz",
  "Tayrona",
  "Tierra Buena. Tintalito I",
  "Tintalito II",
  "Tocarema",
  "Villa Alexandra",
  "Villa Andres",
  "Villa Hermosa",
  "Villa Mendoza",
  "Las Margaritas",
  "Osorio XI",
  "Osorio XII",
  "Portal Americas",
  "Aloha",
  "Alsacia",
  "Aticos de las Americas",
  "Cooperativa de Suboficiales",
  "El Condado de la Paz",
  "Los Pinos de Marsella",
  "Lusitania",
  "Marsella",
  "Nuestra Senora de La Paz",
  "San Jose Occidental",
  "Unidad Oviedo",
  "Urbanizacion Bavaria",
  "Ciudad Alsacia",
  "Arabia",
  "Atahualpa",
  "Bahia Solano",
  "Santiago Batavia",
  "Belen",
  "Betania",
  "Boston",
  "Centenario",
  "Centro A",
  "El Carmen",
  "El Cuco",
  "El Guadual",
  "El Jordan",
  "El Pedregal",
  "El Ruby",
  "El Tapete",
  "Ferrocaja",
  "Flandes",
  "Fontibon Centro",
  "La Cabana",
  "La Giralda",
  "La Laguna",
  "Las Flores",
  "Palestina",
  "Rincon Santo",
  "Santander",
  "Salamanca",
  "San Pedro-Los Robles",
  "Torcoroma",
  "Unidad Residencial Montecarlo",
  "Valle Verde",
  "Veracruz",
  "Versalles",
  "Villa Beatriz",
  "Villa Carmenza",
  "Villemar",
  "Ambalema",
  "Bohios",
  "El Portal",
  "El Refugio",
  "El Triangulo",
  "Florencia",
  "Jerico",
  "La Aldea",
  "La Estacion",
  "La Perla",
  "La Zelfita",
  "Las Brisas",
  "Prados de la Alameda",
  "Puente Grande",
  "San Pablo",
  "Selva Dorada",
  "Villa Liliana",
  "HB",
  "Recodo",
  "Pueblo Nuevo",
  "Moravia",
  "Kasandra",
  "Sabana Grande",
  "Carlos Lleras",
  "La Esperanza Norte",
  "Salitre Nor-Occidental",
  "Sauzalito",
  "El Franco",
  "Granjas de Techo",
  "Montevideo",
  "Paraiso Bavaria",
  "Vision Semiindustrial",
  "Bosque de Modelia",
  "Baleares",
  "Capellania",
  "El Rincon de Modelia",
  "Fuentes del Dorado",
  "Hayuelos",
  "Cofradia",
  "La Felicidad",
  "La Esperanza",
  "Mallorca",
  "Modelia",
  "Modelia Occidental",
  "Santa Cecilia",
  "Tarragona",
  "El Jardin",
  "La Rosita",
  "Puerta de Teja",
  "San Jose",
  "Veracruz",
  "El Bogotano",
  "Acapulco",
  "Bellavista Occidental",
  "La Bonanza",
  "Bosque Popular",
  "Cataluna",
  "Ciudad de Honda",
  "El Dorado-San Joaquin",
  "El Guali",
  "El Laurel",
  "El Paseo",
  "Estrada",
  "La Cabana",
  "La Estradita",
  "La Europa",
  "La Marcela",
  "La Reliquia",
  "Las Ferias",
  "Metropolis",
  "Palo Blanco",
  "Santo Domingo",
  "Andalucia",
  "Ciudad Bachue",
  "Copetroco La Tropical",
  "El Portal del Rio",
  "La Palestina",
  "Tisquesusa",
  "Andalucia",
  "La Espanola",
  "La Serena",
  "Los Cerezos",
  "Luis Carlos Galan",
  "Meissen-Sidauto",
  "Minuto de Dios",
  "Morisco",
  "Paris Gaitan",
  "Primavera Norte",
  "Quirigua",
  "Boyaca",
  "El Carmelo",
  "El Refugio",
  "Florencia",
  "Florida Blanca",
  "La Almeria",
  "La Granja",
  "La Soledad Norte",
  "La Salina",
  "Los Pinos Florencia",
  "Maratu",
  "Paris",
  "Santa Helenita",
  "Santa Maria del Lago",
  "Santa Rosita",
  "Tabora",
  "Veracruz",
  "Zarzamora",
  "El Encanto",
  "El Lujan",
  "El Real",
  "Los Monjes",
  "Normandia",
  "Normandia Occidental",
  "San Ignacio",
  "San Marcos",
  "Santa Cecilia",
  "Villa Luz",
  "Bochica",
  "Bochica Compartir",
  "Bolivia",
  "Ciudadela Colsubsidio",
  "Cortijo",
  "Garces Navas",
  "alamos",
  "alamos Norte",
  "Bosques de Mariana",
  "El Cedro",
  "Garces Navas",
  "Los angeles",
  "Molinos de Viento",
  "Plazuelas del Virrey",
  "San Basilio",
  "Santa Monica",
  "Villa Amalia",
  "Villa Sagrario",
  "Villas de Granada",
  "Villas del Madrigal",
  "Villas del Dorado-San Antonio",
  "Bosques de Granada",
  "Parques de Granada",
  "Andalucia Parques de Granada",
  "Portal de Granada",
  "Rincon de Granada",
  "Granada Club Residencial",
  "La Rotana",
  "Mirador de los Cerezos",
  "Alameda",
  "Centauros del Danubio",
  "El Cedro",
  "El Mirador",
  "El Muelle",
  "El Palmar",
  "El Triangulo",
  "El Verdún",
  "Engativa-Centro",
  "Granjas El Dorado",
  "La Cabana",
  "La Esperanza",
  "La Faena",
  "La Riviera",
  "La Torquigua",
  "Santa Lucia Norte",
  "Las Mercedes",
  "Las Palmas",
  "Linterama",
  "Los Laureles",
  "Los Laureles-Sabanas",
  "El Dorado",
  "Marandú",
  "Porvenir",
  "Puerto Amor-Playas del Jaboque",
  "San Antonio Norte",
  "San Basilio",
  "San Jose Obrero",
  "Santa Librada",
  "Villa Claver I",
  "Villa Claver II",
  "Villa Constanza",
  "Villas del Dorado Norte",
  "Villa Gladys",
  "Villa Mary",
  "Villa Sandra",
  "Villa Teresita",
  "Vina del Mar",
  "El Salitre-Luis Maria Fernandez",
  "San Ignacio-Los Alamos",
  "a\tLa Academia",
  "Guaymaral",
  "Conejera",
  "Gibraltar",
  "Guicani",
  "Mirandela",
  "Nueva Zelandia",
  "Oikos",
  "San Felipe",
  "San Jose de Bavaria",
  "Santa Catalina",
  "Tejares del Norte",
  "Villanova",
  "Villa del Prado",
  "Villa Lucy",
  "Britalia",
  "Britalia San Diego",
  "Calima Norte",
  "Cantagallo",
  "Cantalejo",
  "El Paraiso de los 12 Apostoles",
  "Gilmar",
  "Granada Norte",
  "Granjas de Namur",
  "La Chocita",
  "Los Eliseos",
  "Pijao de Oro",
  "Portales del Norte",
  "San Cipriano",
  "Villa Delia",
  "Vista Bella",
  "Alcala",
  "Atabanza",
  "Bernal",
  "Forero",
  "Cacihia",
  "Canodromo",
  "La Sultana",
  "Libertadores",
  "Los Prados de La Sultana",
  "Madeira",
  "Manuela Arluz",
  "Mazuren",
  "Niza IX",
  "Prado Pinzon",
  "Prado Sur",
  "Prado Veraniego",
  "Prado Veraniego Norte",
  "Prado Veraniego Sur",
  "San Jose del Spring",
  "San Jose del Prado",
  "Santa Helena",
  "Tarragona",
  "Tierra Linda",
  "Victoria Norte",
  "Villa Morena",
  "Alhambra",
  "Batan",
  "El Recreo de los Frailes",
  "Estoril",
  "Ilarco",
  "Malibu",
  "Monaco",
  "Pasadena",
  "Puente Largo",
  "Atenas",
  "Catalayud",
  "Casa Blanca I",
  "Casa Blanca II",
  "Casablanca Norte Suba",
  "Del Monte",
  "El Velero",
  "Escuela de Carabineros",
  "Calatrava",
  "Campania",
  "Ciudad Jardin Norte",
  "Colina Campestre",
  "Colinas de Suba",
  "Cordoba",
  "Covadonga",
  "Gratamira",
  "Iberia",
  "Lagos de Cordoba",
  "Las Villas",
  "Lindaraja",
  "Niza",
  "Niza Norte",
  "Niza Suba",
  "Niza VIII",
  "Prado Jardin",
  "Provenza",
  "Rincon de Iberia",
  "Sotileza",
  "Andes Norte",
  "Club los Lagartos",
  "Coasmedas",
  "Julio Florez",
  "La Alborada",
  "La Floresta Norte",
  "Morato",
  "Nuevo Monterrey",
  "Pontevedra",
  "Potosi",
  "Santa Rosa",
  "San Nicolas",
  "Teusaca",
  "Acacias",
  "Alaska",
  "Alcazar de Suba",
  "Almendros Norte",
  "Alto de la Toma",
  "Bosques de San Jorge",
  "Campanela",
  "Costa Azul",
  "El Pencil",
  "Suba Compartir",
  "El Pinar",
  "Los Lagos",
  "El Portico",
  "El Salitre",
  "Java",
  "La Campiña",
  "La Fontana",
  "Gloria Lara",
  "Las Orquideas",
  "Londres",
  "Miraflores",
  "Monarcas",
  "Navetas",
  "Prados de Suba",
  "Portal de Las Mercedes",
  "Almendros de Suba",
  "Las Flores",
  "Pradera de Suba",
  "Prados de Suba",
  "Rincón de Santa Ines",
  "San Francisco",
  "Santa Isabel",
  "Suba Centro",
  "Tuna Alta",
  "Tuna Baja",
  "Turingia",
  "Vereda Suba Cerros",
  "Villa del Campo",
  "Villa Esperanza",
  "Villa Hermosa",
  "Villa Susana",
  "Alcaparros",
  "Almirante Colon",
  "Almonacid",
  "Altos de Chozica",
  "Altos de la Esperanza",
  "Amberes",
  "Antonio Granados",
  "Arrayanes",
  "Aures I",
  "Aures II",
  "Bochalema",
  "Catalina",
  "Ciudad Hunza",
  "Ciudadela Cafam",
  "Costa Azul",
  "Costa Rica",
  "El Aguinaldo",
  "El Arenal",
  "El Carmen",
  "El Cerezo",
  "El Condor",
  "El Jordan-La Esperanza",
  "El Poa",
  "El Naranjal",
  "El Ocal",
  "El Palmar",
  "El Portico",
  "El Progreso",
  "El Refugio de Suba",
  "El Rubi",
  "El Tabor",
  "Gloria Lara de Echeverri",
  "Guillermo Nunez",
  "Jaime Bermeo",
  "Japon",
  "Java II",
  "La Aguadita",
  "La Alameda",
  "La Aurora",
  "La Chucua",
  "La Esmeralda",
  "La Esperanza",
  "La Estanzuela",
  "La Flor",
  "La Flora",
  "La Manuelita",
  "La Palma",
  "Lagos de Suba",
  "Las Flores",
  "Lombardia",
  "Los Arrayanes",
  "Los Naranjos",
  "Los Nogales",
  "Naranjos Altos",
  "Palma Aldea",
  "Porterrillo",
  "Prados de Santa Barbara",
  "Puerta del Sol",
  "Rincon de Suba",
  "Rincon El Condor",
  "Rincon-Escuela",
  "Riobamba",
  "Rodrigo Lara Bonilla",
  "San Cayetano",
  "San Isidro Norte",
  "San Jorge",
  "San Miguel",
  "San Pedro",
  "Santa Ana de Suba",
  "Taberin",
  "Telecom Arrayanes",
  "Teusaquillo de Suba",
  "Tibabuyes",
  "Trinitaria",
  "Villa Alexandra",
  "Villa Catalina",
  "Villa Elisa",
  "Villa Maria",
  "Villas del Rincon",
  "Atenas",
  "Berlin",
  "Bilbao",
  "Cañiza I",
  "Cañiza II",
  "Cañiza III",
  "Carolina II",
  "Carolina III",
  "El Cedro",
  "Compartir",
  "Fontanar del rio",
  "La Gaitana",
  "La Isabela",
  "Lisboa",
  "Los Nogales de Tibabuyes",
  "Miramar",
  "Nueva Tibabuyes",
  "Nuevo Corinto",
  "Prados de Santa Barbara",
  "Rincon de Boyaca",
  "Sabana de Tibabuyes",
  "San Carlos de Suba",
  "San Carlos de Tibabuyes",
  "San Pedro de Tibabuyes",
  "Santa Cecilia",
  "Santa Rita",
  "Tibabuyes Universal",
  "Toscana",
  "Vereda Suba-Rincon",
  "Vereda Tibabuyes",
  "Verona",
  "Villa Cindy",
  "Villa de las Flores",
  "Villa Gloria",
  "Villa Calasanz",
  "Entre Rios",
  "La Castellana",
  "La Patria",
  "Los Andes",
  "Rionegro",
  "Urbanizacion San Martin",
  "Vizcaya",
  "Doce De Octubre",
  "Jorge Eliecer Gaitan",
  "Jose Joaquin Vargas",
  "La Libertad",
  "Rincon Del Salitre",
  "El Labrador",
  "Metropolis",
  "Modelo Norte",
  "San Fernando",
  "San Miguel",
  "Simon Bolivar",
  "1 De Noviembre",
  "Alcazares Norte",
  "Baquero",
  "Benjamin Herrera",
  "Chapinero Noroccidental",
  "Colombia",
  "Concepción Norte",
  "Juan XXIII Norte",
  "La Aurora",
  "La Esperanza",
  "La Merced Norte",
  "La Paz",
  "Los Alcazares",
  "Muequeta",
  "Polo Club",
  "Quinta Mutis",
  "Rafael Uribe Uribe",
  "San Felipe",
  "Santa Sofia",
  "Siete de Agosto",
  "El Rosario",
  "El Campin",
  "San Luis",
  "Chapinero Occidental",
  "Galerias",
  "Banco Central",
  "Quesada",
  "Belalcazar",
  "Alfonso Lopez Norte",
  "Palermo",
  "La Soledad",
  "Santa teresita",
  "La Magdalena",
  "Teusaquillo",
  "Las Americas",
  "La Estrella",
  "Armenia",
  "Parque Metropolitano",
  "Simon Bolivar",
  "Pablo VI",
  "Nicolas de Federman",
  "Campin Occidental",
  "Rafael Nunez",
  "La Esmeralda",
  "Acevedo Tejada",
  "El Recuerdo",
  "Gran America",
  "Centro Narino",
  "Quinta Paredes",
  "Ortezal",
  "Ciudad Salitre Su-Oriental",
  "Ciudad Salitre Nor-Oriental",
  "Eduardo Santos",
  "El Progreso",
  "El Vergel",
  "Santa Isabel",
  "Veraguas",
  "El Liston",
  "Estacion de la Sabana",
  "La Estanzuela",
  "La Favorita",
  "La Pepita",
  "Paloquemao",
  "Panamericano-La Florida",
  "Ricaurte",
  "Samper Mendoza",
  "San Victorino",
  "Santa Fe",
  "Voto Nacional",
  "el Conjunto Residencial Usatama",
  "Unidad Residencial Colseguros",
  "la Unidad Residencial Sans Facon",
  "Bulevar de Sans Facon",
  "Policarpa",
  "Caracas",
  "Ciudad Berna",
  "Ciudad Jardin",
  "Sevilla",
  "Luna Park",
  "La Hortua",
  "Restrepo",
  "Villa Mayor",
  "San Jorge Central",
  "Cinco de Noviembre",
  "Eduardo Frei",
  "San Antonio",
  "La Fragua",
  "La Fraguita",
  "Santander",
  "La Guaca",
  "Bochica",
  "Carabelas",
  "Ciudad Montes",
  "El Sol",
  "Jazmin",
  "Jorge Gaitan Cortes",
  "Villa Ines",
  "La Asuncion",
  "La Camelia",
  "Los Comuneros",
  "Ponderosa",
  "Primavera",
  "Remanso",
  "San Eusebio",
  "Santa Matilde",
  "Tibana",
  "Torremolinos",
  "Alcala",
  "Alqueria",
  "Autopista Sur",
  "La Coruna",
  "Los Sauces",
  "Muzu",
  "Ospina Perez",
  "Santa Rita",
  "Tejar",
  "Villa del Rosario",
  "Villa Sonia",
  "Barcelona",
  "Bisas del Galan",
  "Camelia Sur",
  "Colon",
  "Galan",
  "La Pradera",
  "La Trinidad",
  "El Arpay La Lira",
  "Milenta",
  "San Francisco",
  "San Gabriel",
  "San Rafael",
  "San Rafael Industrial",
  "Salazar Gomez",
  "Cundinamarca",
  "El Ejido",
  "Gorgonzola",
  "Industrial Centenario",
  "La Florida Occidental",
  "Los Ejidos",
  "Pensilvania",
  "Batallon Caldas",
  "Centro Industrial",
  "Ortezal",
  "Puente Aranda",
  "La Catedral",
  "La Concordia",
  "Las Aguas",
  "Centro Administrativo",
  "Egipto",
  "Belen ",
  "Nueva Santa Fe",
  "Santa Barbara",
  "Bosque de San Carlos",
  "Country Sur",
  "Gustavo Restrepo",
  "Pijaos",
  "San Jose Sur",
  "San Luis Sur",
  "Sosiego Sur",
  "Claret",
  "Bravo Paez",
  "Centenario",
  "Matatigres",
  "Murillo Toro",
  "Olaya",
  "Quiroga",
  "Santa Lucia",
  "Santiago Perez",
  "El Ingles",
  "Villa Mayor Occidental",
  "Colinas",
  "El Pesebre",
  "Granjas de San Pablo",
  "Granjas de Santa Sofia",
  "Jorge Cavelier La Resureccion",
  "Las Lomas",
  "Luis Lopez de Mesa",
  "Marco Fidel Suarez",
  "Rio de Janeiro",
  "San Jorge",
  "Arboleda Sur",
  "Callejon Santa Barbara",
  "Cerros de Oriente",
  "Chircales",
  "Danubio Sur",
  "El Consuelo",
  "El Rosal",
  "El Socorro",
  "Gavaroba",
  "Guiparma",
  "La Merced del Sur",
  "La Picota Occidental",
  "La Playa",
  "Marruecos",
  "Mirador del Sur",
  "Molinos",
  "Nueva Pensilvania Sur",
  "Pradera Sur",
  "Puerto Rico",
  "Sarasota",
  "bochica",
  "Villa Gladys",
  "Villa Morales",
  "San Agustin",
  "Diana Turbay",
  "El Portal",
  "La Esperanza Alta",
  "La Paz",
  "La Picota Oriental",
  "Palermo Sur",
  "La Lira",
  "El Pedregal",
  "Villa Jacky",
  "las Manas",
  "Mochuelo Oriental",
  "El Mochuelo II",
  "Brazuelos de Santo Domingo",
  "Esmeralda",
  "Lagunitas",
  "Paticos",
  "Barranquitos",
  "Arborizadora Baja",
  "Atlanta",
  "La Playa",
  "Madelena",
  "Rafael Escamilla",
  "Santa Helena",
  "Santa Rosa Sur",
  "Villa Helena",
  "Casa linda ",
  "La Coruna",
  "Protecho",
  "San Francisco",
  "Las Acacias",
  "Candelaria La Nueva",
  "Gibraltar",
  "Colmena",
  "La Casona",
  "Juan Jose Rondon",
  "San Luis Sur",
  "San Fernando Sur",
  "Santa Ines de la Acacia",
  "Millan Los Sauces",
  "Puerta del Llano",
  "Sauces",
  "Hortalizas",
  "El Recuerdo",
  "Alvaro Bernal Segura",
  "Lucero Alto",
  "Lucero Medio",
  "Lucero Bajo",
  "Domingo Lain",
  "El Bosque",
  "El Castillo",
  "El Paraiso Mirador",
  "Bella Flor",
  "La Torre",
  "Estrella del Sur",
  "El Triunfo",
  "Gibraltar Sur",
  "Juan Pablo II",
  "La Alameda",
  "La Cabaña",
  "La Escala",
  "Las Manitas",
  "Los Alpes",
  "El Satelite",
  "La Torre",
  "Los Andes de Nutibara",
  "La Estrella de Lagos",
  "Ciudad Milagros",
  "Compartir",
  "Buenavista",
  "Marandu",
  "Meissen",
  "Brisas del Volador",
  "Mexico",
  "Nueva Colombia",
  "Naciones Unidas",
  "Tierra Linda",
  "Vista Hermosa",
  "Rincon del Diamante Villa Gloria",
  "Capri",
  "Arabia",
  "Acapulco",
  "Buenos Aires",
  "Bogota Sur",
  "Divino Niño",
  "Casa de Teja",
  "El Consuelo",
  "El Tesoro",
  "Tesorito",
  "El Mochuelo I",
  "El Reflejo",
  "La Cumbre",
  "Los Duques",
  "Ines Elvira",
  "Monterey",
  "Minuto de Maria",
  "Ocho de Diciembre",
  "Quiba",
  "Potreritos",
  "Republica de Venezuela",
  "Republica de Canada",
  "San Rafael Sur",
  "San Joaquin del Vaticano",
  "Sotavento",
  "Villa Diana Lopez",
  "Bella Estancia",
  "Barlovento",
  "Caracoli",
  "Bonanza Sur",
  "Casa Loma Casavianca",
  "Cerro del Diamante",
  "El Rosal",
  "El Espino",
  "Ismael Perdomo",
  "El Porvenir",
  "El Rincon del Porvenir",
  "Galicia",
  "La Carbonera",
  "Mirador de la Estancia",
  "Mirador de Primavera",
  "Perdomo Alto",
  "Rincon de Galicia",
  "Rincon de la estancia",
  "Rincon de la Valvanera",
  "San Antonio del Mirador",
  "San Isidro",
  "Maria Cano",
  "San Rafael de la Estancia",
  "Santa Viviana",
  "Santo Domingo",
  "Sierra Morena",
  "Arborizadora Alta",
  "Bella Vista",
  "Florida del Sur",
  "Jerusalen",
  "La Pradera",
  "Las Brisas",
  "Potosi",
  "Las Vegas de Potosi",
  "Villas de Bolivar",
  "Verona",
];
